#!/bin/bash

#SBATCH --job-name=eva
#SBATCH --ntasks-per-node=16
#SBATCH --nodes=1
#SBATCH --account uc15

source ~/miniconda3/bin/activate base

cd /gpfs/projects/meteo/WORK/zequi/eva/eva
rm -rf content content.zst

#python ncmls.py esgf_ensemble_test
python ncmls.py esgf_ensemble
#python ncmls.py esgf_dataset_test
python ncmls.py esgf_dataset
cp catalog.xml content
tar --use-compress-program zstd -cf content.zst content/
#zip -r ncmls.zip content
